version: "3.8"

services:

    service-discovery:
        image: ibadullayevali/service-discovery
        container_name: service-discovery
        ports:
            - "8761:8761"
        networks:
            - proxynet

    api-gateway:
        image: ibadullayevali/api-gateway
        container_name: api-gateway
        depends_on:
            - service-discovery
            - rabbit
            - postgres
            - redis
        restart: on-failure
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tasty_pizza
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - SPRING_RABBITMQ_HOST=rabbit
            - SPRING_RABBITMQ_USERNAME=rabbit
            - SPRING_RABBITMQ_PASSWORD=rabbit
            - SPRING_DATA_REDIS_HOST=redis
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
        ports:
            - "8081:8081"
        networks:
            - proxynet

    profile-service:
        container_name: profile-service
        image: ibadullayevali/profile-service
        restart: on-failure
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tasty_pizza
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - SPRING_RABBITMQ_HOST=rabbit
            - SPRING_RABBITMQ_USERNAME=rabbit
            - SPRING_RABBITMQ_PASSWORD=rabbit
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
        depends_on:
            - postgres
            - rabbit
            - service-discovery
        networks:
            - proxynet
        links: 
          - postgres
     
    order-service:
        container_name: order-service
        image: ibadullayevali/menu-orders-service
        restart: on-failure
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tasty_pizza
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
        depends_on:
            - postgres
            - service-discovery
        networks:
            - proxynet
        links:
          - postgres

    postgres:
        platform: linux/arm64/v8
        container_name: postgres
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tasty_pizza
        ports:
          - "5432:5432"
        volumes:
          - postgresdata:/var/lib/postgresql/data
        networks:
            - proxynet

    redis:
        image: redis/redis-stack-server:latest
        networks:
            - proxynet
        volumes:
            - redisdata:/data

    rabbit:
        container_name: rabbit
        image: rabbitmq:3-management
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        ports:
            - "15762:15762"
            - "5762:5762"
        networks:
            - proxynet
        volumes:
            - rabbitdata:/var/lib/rabbitmq/
networks:
    proxynet:
        driver: bridge
volumes:
    postgresdata:
    rabbitdata:
    redisdata:
